class SignInPage < SitePrism::Page
  # set_url '/signup'
  # element :name_field,       "#user_name"
  # element :foo,       "#user_gender_attributes_trans_true"
  # element :foo,       "#user_gender_attributes_trans_false"
  # element :foo,       "#user_gender_attributes_identity"
  # element :foo,       "#user_gender_attributes_cp_false"
  # element :foo,       "#user_gender_attributes_cp_true"
  # element :foo,       "#user_gender_attributes_they"
  # element :foo,       "#user_gender_attributes_their"
  # element :foo,       "#user_gender_attributes_them"
  # element :foo,       "#user_contact_attributes_email"
  # element :foo,       "#user_contact_attributes_phone"
  # element :foo,       "#user_location_attributes_zip"
  # element :foo,       "#user_location_attributes_city"
  # element :foo,       "#user_location_attributes_state"
  # element :foo,       "#user_is_provider_true"
  # element :foo,       "#user_is_provider_false"
  # element :foo,       "#user_food_resource_attributes_currently_offered_true"
  # element :foo,       "#user_food_resource_attributes_currently_offered_false"
  # element :foo,       "#user_shower_resource_attributes_currently_offered_true"
  # element :foo,       "#user_shower_resource_attributes_currently_offered_false"
  # element :foo,       "#user_laundry_resource_attributes_currently_offered_true"
  # element :foo,       "#user_laundry_resource_attributes_currently_offered_false"
  # element :foo,       "#user_housing_resource_attributes_currently_offered_true"
  # element :foo,       "#user_housing_resource_attributes_currently_offered_false"
  # element :foo,       "#user_transportation_resource_attributes_currently_offered_true"
  # element :foo,       "#user_transportation_resource_attributes_currently_offered_false"
  # element :foo,       "#user_buddy_resource_attributes_currently_offered_true"
  # element :foo,       "#user_buddy_resource_attributes_currently_offered_false"
  # element :foo,       "#user_password"
  # element :foo,       "#user_password_confirmation"
  # element :foo,       "#submit_signup "

class EditProfilePage < SitePrism::Page
  # set_url_matcher
  # IDs of 'edit' form elements.

  # element :foo, "#user_name"
  # element :foo, "#user_contact_attributes_email"
  # element :foo, "#user_contact_attributes_phone"
  # element :foo, "#user_location_attributes_zip"
  # element :foo, "#user_location_attributes_city"
  # element :foo, "#user_location_attributes_state"
  # element :foo, "#user_food_resource_attributes_currently_offered_true"
  # element :foo, "#user_food_resource_attributes_currently_offered_false"
  # element :foo, "#user_food_resource_attributes_id"
  # element :foo, "#user_shower_resource_attributes_currently_offered_true"
  # element :foo, "#user_shower_resource_attributes_currently_offered_false"
  # element :foo, "#user_shower_resource_attributes_id"
  # element :foo, "#user_laundry_resource_attributes_currently_offered_true"
  # element :foo, "#user_laundry_resource_attributes_currently_offered_false"
  # element :foo, "#user_laundry_resource_attributes_id"
  # element :foo, "#user_housing_resource_attributes_currently_offered_true"
  # element :foo, "#user_housing_resource_attributes_currently_offered_false"
  # element :foo, "#user_housing_resource_attributes_id"
  # element :foo, "#user_transportation_resource_attributes_currently_offered_true"
  # element :foo, "#user_transportation_resource_attributes_currently_offered_false"
  # element :foo, "#user_transportation_resource_attributes_id"
  # element :foo, "#user_buddy_resource_attributes_currently_offered_true"
  # element :foo, "#user_buddy_resource_attributes_currently_offered_false"
  # element :foo, "#user_buddy_resource_attributes_id"
  # element :foo, "#user_password"
  # element :foo, "#user_password_confirmation"
  # element :foo, "#user_location_attributes_id"
  # element :foo, "#user_contact_attributes_id "
end