class SignUpPage < SitePrism::Page
  set_url '/signup'
  element :name_field,              "input#user_name"
  element :trans_status_radios,     "input[id^='user_gender_attributes_trans']"
  # element :n,                "#user_gender_attributes_identity"
  # element :n,                "#user_gender_attributes_cp_false"
  # element :n,                "#user_gender_attributes_cp_true"
  # element :n,                "#user_gender_attributes_they"
  # element :n,                "#user_gender_attributes_their"
  # element :n,                "#user_gender_attributes_them"
  # element :n,                "#user_contact_attributes_email"
  # element :n,                "#user_contact_attributes_phone"
  # element :n,                "#user_location_attributes_zip"
  # element :n,                "#user_location_attributes_city"
  # element :n,                "#user_location_attributes_state"
  # element :n,                "#user_is_provider_true"
  # element :n,                "#user_is_provider_false"
  # element :n,                "#user_food_resource_attributes_currently_offered_true"
  # element :n,                "#user_food_resource_attributes_currently_offered_false"
  # element :n,                "#user_shower_resource_attributes_currently_offered_true"
  # element :n,                "#user_shower_resource_attributes_currently_offered_false"
  # element :n,                "#user_laundry_resource_attributes_currently_offered_true"
  # element :n,                "#user_laundry_resource_attributes_currently_offered_false"
  # element :n,                "#user_housing_resource_attributes_currently_offered_true"
  # element :n,                "#user_housing_resource_attributes_currently_offered_false"
  # element :n,                "#user_transportation_resource_attributes_currently_offered_true"
  # element :n,                "#user_transportation_resource_attributes_currently_offered_false"
  # element :n,                "#user_buddy_resource_attributes_currently_offered_true"
  # element :n,                "#user_buddy_resource_attributes_currently_offered_false"
  # element :n,                "#user_password"
  # element :n,                "#user_password_confirmation"
  # element :n,                "#submit_signup "

class EditProfilePage < SitePrism::Page
  # set_url_matcher
  # IDs of 'edit' form elements.

  # element :foo, "#user_name"
  # element :foo, "#user_contact_attributes_email"
  # element :foo, "#user_contact_attributes_phone"
  # element :foo, "#user_location_attributes_zip"
  # element :foo, "#user_location_attributes_city"
  # element :foo, "#user_location_attributes_state"
  # element :foo, "#user_food_resource_attributes_currently_offered_true"
  # element :foo, "#user_food_resource_attributes_currently_offered_false"
  # element :foo, "#user_food_resource_attributes_id"
  # element :foo, "#user_shower_resource_attributes_currently_offered_true"
  # element :foo, "#user_shower_resource_attributes_currently_offered_false"
  # element :foo, "#user_shower_resource_attributes_id"
  # element :foo, "#user_laundry_resource_attributes_currently_offered_true"
  # element :foo, "#user_laundry_resource_attributes_currently_offered_false"
  # element :foo, "#user_laundry_resource_attributes_id"
  # element :foo, "#user_housing_resource_attributes_currently_offered_true"
  # element :foo, "#user_housing_resource_attributes_currently_offered_false"
  # element :foo, "#user_housing_resource_attributes_id"
  # element :foo, "#user_transportation_resource_attributes_currently_offered_true"
  # element :foo, "#user_transportation_resource_attributes_currently_offered_false"
  # element :foo, "#user_transportation_resource_attributes_id"
  # element :foo, "#user_buddy_resource_attributes_currently_offered_true"
  # element :foo, "#user_buddy_resource_attributes_currently_offered_false"
  # element :foo, "#user_buddy_resource_attributes_id"
  # element :foo, "#user_password"
  # element :foo, "#user_password_confirmation"
  # element :foo, "#user_location_attributes_id"
  # element :foo, "#user_contact_attributes_id "
end