class SignUpPage < SitePrism::Page
  set_url '/signup'

  elements :error_message,                  ".input-error"
  elements :next_buttons,                    ".wizard-forward"
  element  :name_field,                     "input#user_name"
  element  :name_submit_button,             "button[id^='user_name']"
  elements :trans_status_radios,            "input[id^='user_gender_attributes_trans']"
  element  :trans_status_true,              "#user_gender_attributes_trans_true"
  element  :trans_status_false,             "#user_gender_attributes_trans_false"
  element  :gender_select_binary,           "#binary_genders"
  element  :gender_select_trans_binary,     "#binary_trans_genders"
  element  :gender_select_trans_nonbinary,  "#nonbinary_trans_genders"
  element  :gender_identity_field,          "#user_gender_attributes_identity"
  element  :custom_pronouns_true,           "#user_gender_attributes_cp_false"
  element  :custom_pronouns_false,          "#user_gender_attributes_cp_true"
  element  :custom_pronouns_they,           "#user_gender_attributes_they"
  element  :custom_pronouns_their,          "#user_gender_attributes_their"
  element  :custom_pronouns_them,           "#user_gender_attributes_them"
  element  :email_field,                    "#user_contact_attributes_email"
  element  :phone_field,                    "#user_contact_attributes_phone"
  element  :zip_field,                      "#user_location_attributes_zip"
  element  :city_field,                     "#user_location_attributes_city"
  element  :state_field,                    "#user_location_attributes_state"
  element  :provider_status_true,           "#user_is_provider_true"
  element  :provider_status_false,          "#user_is_provider_false"
  element  :offers_food_true,               "#user_food_resource_attributes_currently_offered_true"
  element  :offers_food_false,              "#user_food_resource_attributes_currently_offered_false"
  element  :offers_shower_true,             "#user_shower_resource_attributes_currently_offered_true"
  element  :offers_shower_false,            "#user_shower_resource_attributes_currently_offered_false"
  element  :offers_laundry_true,            "#user_laundry_resource_attributes_currently_offered_true"
  element  :offers_laundry_false,           "#user_laundry_resource_attributes_currently_offered_false"
  element  :offers_housing_true,            "#user_housing_resource_attributes_currently_offered_true"
  element  :offers_housing_false,           "#user_housing_resource_attributes_currently_offered_false"
  element  :offers_transportation_true,     "#user_transportation_resource_attributes_currently_offered_true"
  element  :offers_transportation_false,    "#user_transportation_resource_attributes_currently_offered_false"
  element  :offers_buddy_true,              "#user_buddy_resource_attributes_currently_offered_true"
  element  :offers_buddy_false,             "#user_buddy_resource_attributes_currently_offered_false"
  element  :password_field,                 "#user_password"
  element  :password_confirmation_field,    "#user_password_confirmation"
  element  :submit_button,                  "#submit_signup"
end

class HomePage < SitePrism::Page
  set_url '/'
end